# Generated by Django 3.1.4 on 2021-01-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaBin',
            fields=[
                ('name_issuer', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=100)),
                ('allowedCaptures_name', models.CharField(max_length=100)),
                ('allowedCaptures_code', models.IntegerField()),
                ('usages_name', models.CharField(max_length=100)),
                ('usages_code', models.IntegerField()),
                ('services_name', models.CharField(max_length=100)),
                ('services_isExchangeableOffer', models.BooleanField(default=False)),
            ],
        ),
    ]
